package com.pojos;
// Generated May 30, 2018 3:50:41 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Artiste generated by hbm2java
 */
@Entity
@Table(name="artiste"
    ,catalog="medartiste"
)
public class Artiste  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String pass;
     private String email;
     private String nom;
     private String prenom;
     private String tel;
     private String adresse;
     private String bio;

    public Artiste() {
    }

    public Artiste(String login, String pass, String email, String nom, String prenom, String tel, String adresse, String bio) {
       this.login = login;
       this.pass = pass;
       this.email = email;
       this.nom = nom;
       this.prenom = prenom;
       this.tel = tel;
       this.adresse = adresse;
       this.bio = bio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Login", nullable=false, length=30)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="Pass", nullable=false, length=30)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="Email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="Nom", nullable=false, length=30)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="Prenom", nullable=false, length=30)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="Tel", nullable=false, length=30)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="Adresse", nullable=false, length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="Bio", nullable=false, length=3000)
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }




}


