package com.pojos;
// Generated May 30, 2018 3:50:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expos generated by hbm2java
 */
@Entity
@Table(name="expos"
    ,catalog="medartiste"
)
public class Expos  implements java.io.Serializable {


     private Integer id;
     private String titre;
     private String sousTitre;
     private String description;
     private String lieu;
     private Date date;
     private int idFk;

    public Expos() {
    }

    public Expos(String titre, String sousTitre, String description, String lieu, Date date, int idFk) {
       this.titre = titre;
       this.sousTitre = sousTitre;
       this.description = description;
       this.lieu = lieu;
       this.date = date;
       this.idFk = idFk;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Titre", nullable=false, length=50)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="Sous_titre", nullable=false, length=50)
    public String getSousTitre() {
        return this.sousTitre;
    }
    
    public void setSousTitre(String sousTitre) {
        this.sousTitre = sousTitre;
    }

    
    @Column(name="Description", nullable=false, length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Lieu", nullable=false, length=50)
    public String getLieu() {
        return this.lieu;
    }
    
    public void setLieu(String lieu) {
        this.lieu = lieu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="Id_fk", nullable=false)
    public int getIdFk() {
        return this.idFk;
    }
    
    public void setIdFk(int idFk) {
        this.idFk = idFk;
    }




}


