package com.pojos;
// Generated May 30, 2018 3:50:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oeuvres generated by hbm2java
 */
@Entity
@Table(name="oeuvres"
    ,catalog="medartiste"
)
public class Oeuvres  implements java.io.Serializable {


     private Integer id;
     private String toile;
     private String taille;
     private String description;
     private double prix;
     private Date date;
     private String etat;
     private String code;
     private int idFk;

    public Oeuvres() {
    }

    public Oeuvres(String toile, String taille, String description, double prix, Date date, String etat, String code, int idFk) {
       this.toile = toile;
       this.taille = taille;
       this.description = description;
       this.prix = prix;
       this.date = date;
       this.etat = etat;
       this.code = code;
       this.idFk = idFk;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Toile", nullable=false, length=100)
    public String getToile() {
        return this.toile;
    }
    
    public void setToile(String toile) {
        this.toile = toile;
    }

    
    @Column(name="Taille", nullable=false, length=100)
    public String getTaille() {
        return this.taille;
    }
    
    public void setTaille(String taille) {
        this.taille = taille;
    }

    
    @Column(name="Description", nullable=false, length=3000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Prix", nullable=false, precision=22, scale=0)
    public double getPrix() {
        return this.prix;
    }
    
    public void setPrix(double prix) {
        this.prix = prix;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="Etat", nullable=false, length=30)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="Code", nullable=false, length=10)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="Id_fk", nullable=false)
    public int getIdFk() {
        return this.idFk;
    }
    
    public void setIdFk(int idFk) {
        this.idFk = idFk;
    }




}


