package com.pojos;
// Generated May 30, 2018 3:50:41 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visites generated by hbm2java
 */
@Entity
@Table(name="visites"
    ,catalog="medartiste"
)
public class Visites  implements java.io.Serializable {


     private Integer id;
     private int visitesJour;
     private Date date;

    public Visites() {
    }

    public Visites(int visitesJour, Date date) {
       this.visitesJour = visitesJour;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Visites_jour", nullable=false)
    public int getVisitesJour() {
        return this.visitesJour;
    }
    
    public void setVisitesJour(int visitesJour) {
        this.visitesJour = visitesJour;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


